services:
  postgres:
    image: postgres:16
    container_name: moodle_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - moodle_network
    restart: unless-stopped

  php-fpm:
    build: 
      context: ./php
      dockerfile: Dockerfile
    container_name: moodle_php
    volumes:
      - ./moodledata:/var/moodledata
      - moodle_files:/var/www/html
    environment:
      DB_TYPE: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      MOODLE_URL: ${MOODLE_URL}
    depends_on:
      - postgres
    networks:
      - moodle_network
    restart: unless-stopped

  nginx:
    image: nginx:1.28
    container_name: moodle_nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - moodle_files:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - moodle_network
    restart: unless-stopped

networks:
  moodle_network:
    driver: bridge

volumes:
  moodle_files: